default_platform :mac

platform :mac do

  ############################ PRE ############################

  before_all do
  end

  ######################## SETUP LANES ########################

  desc "Setup development"
  lane :setup do
  end

  desc "Setup release developer id account settings. (only use admin)"
  lane :setup_release_id do
    # Update Project Team
    update_project_team(
      path: "Clipiero.xcodeproj",
      teamid: "BBCHAJ584H"
    )
    # Update Provisioning Profile
    update_provisioning_profile_specifier(
      xcodeproj: "Clipiero.xcodeproj",
      new_specifier: "ClipieroDistribution",
      configuration: "Release",
      target: "^Clipiero$"
    )
  end

  ####################### PUBLIC LANES ########################

  desc "Runs all the tests"
  lane :test do
    scan_clipiero
  end
  
  desc "Release"
  lane :release do
    # TODO: Use :codesigning_identity options (Developer ID Application: Shunsuke Furubayashi (BBCHAJ584H))
    # TODO: Use :export_method options (developer-id)
  end

  ####################### PRIVATE LANES ########################

  private_lane :scan_clipiero do
    scan(
      project: "Clipiero.xcodeproj",
      scheme: "Clipiero",
      verbose: true,
      clean: true
    )
  end

  ############################ POST ############################

  after_all do |lane|
  end

  error do |lane, exception|
  end
end
